version: "3.8"

services:
  #Servizio del database dell'intera applicazione
  database:
    platform: linux/x86_64
    image: mongo:4.0
    container_name: mongodb_taxMS
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    env_file:
      - .env
    restart: "no"
    networks:
      - my-network




  taxService:
    platform: linux/x86_64
    image: openjdk:17-jdk-alpine
    container_name: TAX_SERVICE
    ports:
      - "8084:8080"
      - "8004:8000"
    expose:
      - "8004"
    depends_on:
      - database
    networks:
      - my-network
    volumes:
      - ./build/libs/TaxMS-0.0.1-SNAPSHOT.jar:/app/app.jar
    working_dir: /app
    entrypoint: java -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8004 -jar /app/app.jar



networks:
  my-network:
    driver:
      "bridge"

volumes:
  mongodb_data: